# Generated by Django 4.0.6 on 2022-07-24 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supers',
            old_name='Primary_ability',
            new_name='primary_ability',
        ),
    ]
